# https://stackoverflow.com/questions/75560681/how-to-exclude-multiple-directories-in-pre-commit
exclude: |
  (?x)^(
      .*/migrations/.*|
      .github/.*|
      .*/node_modules/.*|
      frontend/.*
  )$
repos:
  - repo: https://github.com/PyCQA/isort
    rev: "5.12.0"
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: "v2.0.1"
    hooks:
      - id: autopep8

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
      - id: detect-private-key

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: ["--py3-plus", "--py36-plus"]

  # TODO/NOTE: disable until backend is merged with main
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v3.0.0-alpha.4
  #   hooks:
  #     - id: prettier
