version: "3.9"

services:
  backend:
    image: ghcr.io/bentenopsballeballe/ez-allocate-backend:dev-backend
    build:
      context: backend
      dockerfile: ./Dockerfile.dev
    ports:
      - 8000:8000
    environment: &backend_env_vars
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      CORS_ALLOWED_ORIGINS: https://ez-allocate-git-frontend-benten.vercel.app,https://ez-allocate.vercel.app
    depends_on:
      - redis
    volumes: &backend_volumes
      - "./backend/mock-db.sqlite3:/backend/mock-db.sqlite3"
      - "./.secrets/public.pem:/.secrets/public.pem"
    secrets:
      - source: jwt_public_key
        target: /.secrets/public.pem

  auth:
    image: ghcr.io/bentenopsballeballe/ez-allocate-auth:latest
    build:
      context: ./auth
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./auth/src:/app/src
    secrets:
      - jwt_private_key
      - jwt_public_key

  celery-worker:
    image: ghcr.io/bentenopsballeballe/ez-allocate-backend:dev-backend
    entrypoint: celery -A ez_allocate_backend worker -l info
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - redis
      - backend
    environment: *backend_env_vars
    volumes: *backend_volumes

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

secrets:
  jwt_private_key:
    file: ".secrets/private.pem"
  jwt_public_key: # i know public key isnt sensitive but eh.
    file: ".secrets/public.pem"
