version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - AUTH_URL=/
      - ALLOCATE_URL=/
    networks:
      - proxy-tier
      - frontend-backend

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    depends_on:
      - frontend
      - backend

    ports:
      - '80:80'
    networks:
      - proxy-tier

  backend:
    image: ghcr.io/bentenopsballeballe/ez-allocate-backend:dev-backend
    build:
      context: backend
      dockerfile: ./Dockerfile.dev
    ports:
      - 8000:8000
    networks:
      - proxy-tier
      - frontend-backend

networks:
  frontend-backend:
  proxy-tier:
