version: "3.9"

services:
  backend:
    image: ghcr.io/bentenopsballeballe/ez-allocate-backend:latest
    build:
      context: backend
      dockerfile: ./Dockerfile.dev
    ports:
      - 8000:8000
