version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - AUTH_URL=/
      - ALLOCATE_URL=/

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_started

    ports:
      - '6000:80'

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./auth:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000

  backend:
    image: ghcr.io/bentenopsballeballe/ez-allocate-backend:dev-backend
    # build:
    #   context: backend
    #   dockerfile: ./Dockerfile.dev
    ports:
      - 8000:8000
