[pycodestyle]
count = true
ignore = "E226,E302,E41"
max-line-length = 120
statistics = true

[flake8]
max-line-length = 120
exclude = ".git,__pycache__"


[isort]
line_length = 79
balanced_wrapping = true
