# Generated by Django 4.1.6 on 2023-02-27 11:00

import common_models.utils.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allotted_lecture_hours', models.SmallIntegerField(default=0)),
                ('allotted_tutorial_hours', models.SmallIntegerField(default=0)),
                ('allotted_practical_hours', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_number', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('course_code', models.SlugField(max_length=10, unique=True)),
                ('credits', models.SmallIntegerField()),
                ('course_type', models.CharField(choices=[('CORE', 'Core'), ('ELEC', 'Elective')], max_length=4)),
                ('programme', models.CharField(max_length=20)),
                ('original_lecture_hours', models.SmallIntegerField()),
                ('original_tutorial_hours', models.SmallIntegerField()),
                ('original_practical_hours', models.SmallIntegerField()),
                ('number_of_lecture_batches', models.SmallIntegerField()),
                ('number_of_practical_or_tutorial_batches', models.SmallIntegerField()),
                ('allotment_status', models.CharField(choices=[('NONE', 'None'), ('PART', 'Partial'), ('FULL', 'Full')], default='NONE', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('preferred_mode', models.CharField(default='LTP', max_length=3, validators=[common_models.utils.validators.teacher_model_validate_ltp_preference])),
                ('assigned_status', models.CharField(choices=[('NONE', 'None'), ('PART', 'Partial'), ('FULL', 'Full')], default='NONE', max_length=4)),
                ('subject_choices', models.ManyToManyField(through='common_models.Choices', to='common_models.subject')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='allotted_teachers',
            field=models.ManyToManyField(through='common_models.Allotment', to='common_models.teacher'),
        ),
        migrations.AddField(
            model_name='choices',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_models.subject'),
        ),
        migrations.AddField(
            model_name='choices',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_models.teacher'),
        ),
        migrations.AddField(
            model_name='allotment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_models.subject'),
        ),
        migrations.AddField(
            model_name='allotment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_models.teacher'),
        ),
    ]
