# Generated by Django 4.1.6 on 2023-02-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='allotment_status',
            new_name='_allotment_status',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='assigned_status',
            new_name='_assigned_status',
        ),
    ]
