# Generated by Django 4.1.6 on 2023-02-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='course_code',
            field=models.SlugField(max_length=10, unique=True),
        ),
    ]
