# Generated by Django 4.1.6 on 2023-03-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0002_rename_allotment_status_subject__allotment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='_allotment_status',
            field=models.CharField(choices=[('NONE', 'None'), ('PART', 'Partial'), ('FULL', 'Full'), ('ERRR', 'Error')], default='NONE', max_length=4),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='_assigned_status',
            field=models.CharField(choices=[('NONE', 'None'), ('PART', 'Partial'), ('FULL', 'Full'), ('ERRR', 'Error')], default='NONE', max_length=4),
        ),
    ]
