# Generated by Django 4.1.6 on 2023-02-15 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0002_alter_subject_course_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='prefferred_mode',
            new_name='preferred_mode',
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_number', models.SmallIntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_models.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_models.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allotted_lectures_hours', models.SmallIntegerField()),
                ('allotted_tutorial_hours', models.SmallIntegerField()),
                ('allotted_practical_hours', models.SmallIntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_models.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_models.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='allotted_teachers',
            field=models.ManyToManyField(through='common_models.Allotment', to='common_models.teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject_choices',
            field=models.ManyToManyField(through='common_models.Choices', to='common_models.subject'),
        ),
    ]
