# Generated by Django 4.1.6 on 2023-03-13 05:14

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):
    dependencies = [
        ("common_models", "0003_alter_subject__allotment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="email",
            field=models.EmailField(
                default="null@null.null", max_length=254, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="allotment",
            name="allotted_lecture_hours",
            field=models.SmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:\\d+)*\\Z"),
                        code="number contains decimals",
                        message=None,
                    ),
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="allotment",
            name="allotted_practical_hours",
            field=models.SmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:\\d+)*\\Z"),
                        code="number contains decimals",
                        message=None,
                    ),
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(14),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="allotment",
            name="allotted_tutorial_hours",
            field=models.SmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:\\d+)*\\Z"),
                        code="number contains decimals",
                        message=None,
                    ),
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(14),
                ],
            ),
        ),
    ]
