# Generated by Django 4.1.6 on 2023-03-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "common_models",
            "0004_teacher_email_alter_allotment_allotted_lecture_hours_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CeleryFileResults",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("filename", models.SlugField(max_length=80)),
                ("file", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("has_been_downloaded_yet", models.BooleanField(default=False)),
            ],
        ),
    ]
