# Generated by Django 4.1.6 on 2023-03-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common_models", "0005_celeryfileresults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="celeryfileresults",
            name="id",
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
