export const subjects = [
  {
    id: "CSET101",
    name: "Computational Thinking and Programming",
    credits: 5,
    type: "Core",
    programme: "BTECH",
    original_lecture: 16,
    original_tutorial: 30,
    original_practical: 120,
    lectureBatches: 8,
    tutLabBatches: 30,
    allotedLecture: 10,
    allotedTutorial: 4,
    allotedPractical: 2,
    allotmentStatus: "PARTIAL",
  },
  {
    id: "CSET102",
    name: "Devops",
    credits: 6,
    type: "Elective",
    programme: "BTECH",
    original_lecture: 2,
    original_tutorial: 2,
    original_practical: 4,
    lectureBatches: 1,
    tutLabBatches: 1,
    allotedLecture: 0,
    allotedTutorial: 0,
    allotedPractical: 0,
    allotmentStatus: "NONE",
  },
];
