export const subjects = [
    {
        id: "CSET602",
        name: "nullam molestie nibh",
        type: "Core",
        programme: "PHD",
        original_lecture: 0,
        original_tutorial: 2,
        original_practical: 2,
        credits: 3,
        lecture_batches: 0,
        tutorial_batches: 16,
        total_lecture: 0,
        total_tutorial: 32,
        total_practical: 32,
        alloted_lecture: 0,
        alloted_tutorial: 6,
        alloted_practical: 6,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2efc13ae3c1d0003e8" },
    },
    {
        id: "CSET431",
        name: "odio condimentum id",
        type: "Elective",
        programme: "BCA",
        original_lecture: 2,
        original_tutorial: 0,
        original_practical: 2,
        credits: 3,
        lecture_batches: 6,
        tutorial_batches: 12,
        total_lecture: 12,
        total_tutorial: 0,
        total_practical: 24,
        alloted_lecture: 2,
        alloted_tutorial: 0,
        alloted_practical: 6,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2efc13ae3c1d0003e9" },
    },
    {
        id: "CSET045",
        name: "quisque porta volutpat",
        type: "Core",
        programme: "PHD",
        original_lecture: 3,
        original_tutorial: 2,
        original_practical: 4,
        credits: 7,
        lecture_batches: 2,
        tutorial_batches: 10,
        total_lecture: 6,
        total_tutorial: 20,
        total_practical: 40,
        alloted_lecture: 5,
        alloted_tutorial: 5,
        alloted_practical: 40,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2efc13ae3c1d0003ea" },
    },
    {
        id: "CSET074",
        name: "nascetur ridiculus",
        type: "Core",
        programme: "MTECH",
        original_lecture: 2,
        original_tutorial: 0,
        original_practical: 4,
        credits: 4,
        lecture_batches: 5,
        tutorial_batches: 4,
        total_lecture: 10,
        total_tutorial: 0,
        total_practical: 16,
        alloted_lecture: 5,
        alloted_tutorial: 0,
        alloted_practical: 7,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2efc13ae3c1d0003eb" },
    },
    {
        id: "CSET953",
        name: "est phasellus",
        type: "Core",
        programme: "MTECH",
        original_lecture: 1,
        original_tutorial: 2,
        original_practical: 4,
        credits: 5,
        lecture_batches: 2,
        tutorial_batches: 3,
        total_lecture: 2,
        total_tutorial: 6,
        total_practical: 12,
        alloted_lecture: 2,
        alloted_tutorial: 2,
        alloted_practical: 5,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2efc13ae3c1d0003ec" },
    },
    {
        id: "CSET642",
        name: "velit donec",
        type: "Elective",
        programme: "MTECH",
        original_lecture: 3,
        original_tutorial: 0,
        original_practical: 0,
        credits: 3,
        lecture_batches: 4,
        tutorial_batches: 0,
        total_lecture: 12,
        total_tutorial: 0,
        total_practical: 0,
        alloted_lecture: 11,
        alloted_tutorial: 0,
        alloted_practical: 0,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2efc13ae3c1d0003ed" },
    },
    {
        id: "CSET472",
        name: "bibendum felis",
        type: "Elective",
        programme: "BCA",
        original_lecture: 0,
        original_tutorial: 1,
        original_practical: 4,
        credits: 3,
        lecture_batches: 0,
        tutorial_batches: 18,
        total_lecture: 0,
        total_tutorial: 18,
        total_practical: 72,
        alloted_lecture: 0,
        alloted_tutorial: 3,
        alloted_practical: 26,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2efc13ae3c1d0003ee" },
    },
    {
        id: "CSET255",
        name: "ullamcorper purus sit",
        type: "Core",
        programme: "PHD",
        original_lecture: 4,
        original_tutorial: 1,
        original_practical: 2,
        credits: 6,
        lecture_batches: 5,
        tutorial_batches: 10,
        total_lecture: 20,
        total_tutorial: 10,
        total_practical: 20,
        alloted_lecture: 14,
        alloted_tutorial: 5,
        alloted_practical: 11,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2efc13ae3c1d0003ef" },
    },
    {
        id: "CSET221",
        name: "ullamcorper augue a",
        type: "Core",
        programme: "BCA",
        original_lecture: 1,
        original_tutorial: 0,
        original_practical: 2,
        credits: 2,
        lecture_batches: 1,
        tutorial_batches: 12,
        total_lecture: 1,
        total_tutorial: 0,
        total_practical: 24,
        alloted_lecture: 0,
        alloted_tutorial: 0,
        alloted_practical: 11,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2efc13ae3c1d0003f0" },
    },
    {
        id: "CSET386",
        name: "in congue",
        type: "Core",
        programme: "PHD",
        original_lecture: 0,
        original_tutorial: 2,
        original_practical: 2,
        credits: 3,
        lecture_batches: 0,
        tutorial_batches: 4,
        total_lecture: 0,
        total_tutorial: 8,
        total_practical: 8,
        alloted_lecture: 0,
        alloted_tutorial: 8,
        alloted_practical: 4,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2efc13ae3c1d0003f1" },
    },
    {
        id: "CSET276",
        name: "eros elementum pellentesque",
        type: "Core",
        programme: "BCA",
        original_lecture: 2,
        original_tutorial: 0,
        original_practical: 0,
        credits: 2,
        lecture_batches: 4,
        tutorial_batches: 0,
        total_lecture: 8,
        total_tutorial: 0,
        total_practical: 0,
        alloted_lecture: 3,
        alloted_tutorial: 0,
        alloted_practical: 0,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2efc13ae3c1d0003f2" },
    },
    {
        id: "CSET734",
        name: "diam cras pellentesque",
        type: "Core",
        programme: "PHD",
        original_lecture: 0,
        original_tutorial: 1,
        original_practical: 2,
        credits: 2,
        lecture_batches: 0,
        tutorial_batches: 11,
        total_lecture: 0,
        total_tutorial: 11,
        total_practical: 22,
        alloted_lecture: 0,
        alloted_tutorial: 4,
        alloted_practical: 10,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2efc13ae3c1d0003f3" },
    },
    {
        id: "CSET277",
        name: "consequat ut",
        type: "Elective",
        programme: "MTECH",
        original_lecture: 4,
        original_tutorial: 0,
        original_practical: 0,
        credits: 4,
        lecture_batches: 1,
        tutorial_batches: 0,
        total_lecture: 4,
        total_tutorial: 0,
        total_practical: 0,
        alloted_lecture: 4,
        alloted_tutorial: 0,
        alloted_practical: 0,
        allotment_status: "FULL",
        _id: { $oid: "63fa0e2efc13ae3c1d0003f4" },
    },
    {
        id: "CSET171",
        name: "condimentum curabitur",
        type: "Core",
        programme: "PHD",
        original_lecture: 0,
        original_tutorial: 0,
        original_practical: 4,
        credits: 2,
        lecture_batches: 0,
        tutorial_batches: 1,
        total_lecture: 0,
        total_tutorial: 0,
        total_practical: 4,
        alloted_lecture: 0,
        alloted_tutorial: 0,
        alloted_practical: 1,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2efc13ae3c1d0003f5" },
    },
    {
        id: "CSET024",
        name: "posuere cubilia",
        type: "Core",
        programme: "BCA",
        original_lecture: 1,
        original_tutorial: 1,
        original_practical: 0,
        credits: 2,
        lecture_batches: 1,
        tutorial_batches: 9,
        total_lecture: 1,
        total_tutorial: 9,
        total_practical: 0,
        alloted_lecture: 0,
        alloted_tutorial: 8,
        alloted_practical: 0,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2efc13ae3c1d0003f6" },
    },
    {
        id: "CSET053",
        name: "ante ipsum",
        type: "Core",
        programme: "PHD",
        original_lecture: 2,
        original_tutorial: 2,
        original_practical: 2,
        credits: 5,
        lecture_batches: 6,
        tutorial_batches: 14,
        total_lecture: 12,
        total_tutorial: 28,
        total_practical: 28,
        alloted_lecture: 1,
        alloted_tutorial: 21,
        alloted_practical: 13,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2efc13ae3c1d0003f7" },
    },
    {
        id: "CSET092",
        name: "cras non",
        type: "Elective",
        programme: "MTECH",
        original_lecture: 3,
        original_tutorial: 1,
        original_practical: 4,
        credits: 6,
        lecture_batches: 3,
        tutorial_batches: 16,
        total_lecture: 9,
        total_tutorial: 16,
        total_practical: 64,
        alloted_lecture: 3,
        alloted_tutorial: 7,
        alloted_practical: 2,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2efc13ae3c1d0003f8" },
    },
    {
        id: "CSET859",
        name: "pede posuere",
        type: "Core",
        programme: "PHD",
        original_lecture: 1,
        original_tutorial: 2,
        original_practical: 0,
        credits: 3,
        lecture_batches: 5,
        tutorial_batches: 4,
        total_lecture: 5,
        total_tutorial: 8,
        total_practical: 0,
        alloted_lecture: 4,
        alloted_tutorial: 5,
        alloted_practical: 0,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2efc13ae3c1d0003f9" },
    },
    {
        id: "CSET364",
        name: "nullam molestie",
        type: "Core",
        programme: "PHD",
        original_lecture: 2,
        original_tutorial: 0,
        original_practical: 0,
        credits: 2,
        lecture_batches: 3,
        tutorial_batches: 0,
        total_lecture: 6,
        total_tutorial: 0,
        total_practical: 0,
        alloted_lecture: 5,
        alloted_tutorial: 0,
        alloted_practical: 0,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2efc13ae3c1d0003fa" },
    },
    {
        id: "CSET622",
        name: "tortor id",
        type: "Elective",
        programme: "MTECH",
        original_lecture: 2,
        original_tutorial: 2,
        original_practical: 2,
        credits: 5,
        lecture_batches: 5,
        tutorial_batches: 12,
        total_lecture: 10,
        total_tutorial: 24,
        total_practical: 24,
        alloted_lecture: 8,
        alloted_tutorial: 22,
        alloted_practical: 14,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2efc13ae3c1d0003fb" },
    },
    {
        id: "CSET424",
        name: "rutrum nulla",
        type: "Elective",
        programme: "BTECH",
        original_lecture: 4,
        original_tutorial: 2,
        original_practical: 4,
        credits: 8,
        lecture_batches: 1,
        tutorial_batches: 15,
        total_lecture: 4,
        total_tutorial: 30,
        total_practical: 60,
        alloted_lecture: 3,
        alloted_tutorial: 15,
        alloted_practical: 20,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d0003fc" },
    },
    {
        id: "CSET396",
        name: "sed tincidunt eu",
        type: "Core",
        programme: "BTECH",
        original_lecture: 1,
        original_tutorial: 2,
        original_practical: 2,
        credits: 4,
        lecture_batches: 1,
        tutorial_batches: 8,
        total_lecture: 1,
        total_tutorial: 16,
        total_practical: 16,
        alloted_lecture: 0,
        alloted_tutorial: 7,
        alloted_practical: 16,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d0003fd" },
    },
    {
        id: "CSET102",
        name: "lectus pellentesque",
        type: "Core",
        programme: "PHD",
        original_lecture: 0,
        original_tutorial: 0,
        original_practical: 4,
        credits: 2,
        lecture_batches: 0,
        tutorial_batches: 2,
        total_lecture: 0,
        total_tutorial: 0,
        total_practical: 8,
        alloted_lecture: 0,
        alloted_tutorial: 0,
        alloted_practical: 3,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d0003fe" },
    },
    {
        id: "CSET477",
        name: "nulla ac enim",
        type: "Elective",
        programme: "BCA",
        original_lecture: 3,
        original_tutorial: 0,
        original_practical: 0,
        credits: 3,
        lecture_batches: 2,
        tutorial_batches: 0,
        total_lecture: 6,
        total_tutorial: 0,
        total_practical: 0,
        alloted_lecture: 6,
        alloted_tutorial: 0,
        alloted_practical: 0,
        allotment_status: "FULL",
        _id: { $oid: "63fa0e2ffc13ae3c1d0003ff" },
    },
    {
        id: "CSET592",
        name: "nullam porttitor",
        type: "Elective",
        programme: "PHD",
        original_lecture: 0,
        original_tutorial: 2,
        original_practical: 0,
        credits: 2,
        lecture_batches: 0,
        tutorial_batches: 7,
        total_lecture: 0,
        total_tutorial: 14,
        total_practical: 0,
        alloted_lecture: 0,
        alloted_tutorial: 10,
        alloted_practical: 0,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000400" },
    },
    {
        id: "CSET511",
        name: "sem sed sagittis",
        type: "Core",
        programme: "BCA",
        original_lecture: 2,
        original_tutorial: 1,
        original_practical: 4,
        credits: 5,
        lecture_batches: 6,
        tutorial_batches: 11,
        total_lecture: 12,
        total_tutorial: 11,
        total_practical: 44,
        alloted_lecture: 9,
        alloted_tutorial: 9,
        alloted_practical: 26,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000401" },
    },
    {
        id: "CSET636",
        name: "ipsum aliquam non",
        type: "Elective",
        programme: "PHD",
        original_lecture: 4,
        original_tutorial: 0,
        original_practical: 0,
        credits: 4,
        lecture_batches: 3,
        tutorial_batches: 0,
        total_lecture: 12,
        total_tutorial: 0,
        total_practical: 0,
        alloted_lecture: 7,
        alloted_tutorial: 0,
        alloted_practical: 0,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000402" },
    },
    {
        id: "CSET681",
        name: "eu magna",
        type: "Elective",
        programme: "MTECH",
        original_lecture: 4,
        original_tutorial: 2,
        original_practical: 4,
        credits: 8,
        lecture_batches: 4,
        tutorial_batches: 9,
        total_lecture: 16,
        total_tutorial: 18,
        total_practical: 36,
        alloted_lecture: 15,
        alloted_tutorial: 13,
        alloted_practical: 11,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000403" },
    },
    {
        id: "CSET824",
        name: "lectus pellentesque",
        type: "Elective",
        programme: "BCA",
        original_lecture: 2,
        original_tutorial: 2,
        original_practical: 2,
        credits: 5,
        lecture_batches: 2,
        tutorial_batches: 7,
        total_lecture: 4,
        total_tutorial: 14,
        total_practical: 14,
        alloted_lecture: 3,
        alloted_tutorial: 9,
        alloted_practical: 12,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000404" },
    },
    {
        id: "CSET524",
        name: "vivamus tortor",
        type: "Core",
        programme: "BCA",
        original_lecture: 2,
        original_tutorial: 2,
        original_practical: 0,
        credits: 4,
        lecture_batches: 5,
        tutorial_batches: 12,
        total_lecture: 10,
        total_tutorial: 24,
        total_practical: 0,
        alloted_lecture: 6,
        alloted_tutorial: 8,
        alloted_practical: 0,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000405" },
    },
    {
        id: "CSET664",
        name: "vestibulum sagittis",
        type: "Elective",
        programme: "PHD",
        original_lecture: 1,
        original_tutorial: 2,
        original_practical: 0,
        credits: 3,
        lecture_batches: 3,
        tutorial_batches: 6,
        total_lecture: 3,
        total_tutorial: 12,
        total_practical: 0,
        alloted_lecture: 0,
        alloted_tutorial: 2,
        alloted_practical: 0,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000406" },
    },
    {
        id: "CSET296",
        name: "pede justo lacinia",
        type: "Elective",
        programme: "BTECH",
        original_lecture: 0,
        original_tutorial: 1,
        original_practical: 0,
        credits: 1,
        lecture_batches: 0,
        tutorial_batches: 12,
        total_lecture: 0,
        total_tutorial: 12,
        total_practical: 0,
        alloted_lecture: 0,
        alloted_tutorial: 4,
        alloted_practical: 0,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000407" },
    },
    {
        id: "CSET049",
        name: "vitae ipsum",
        type: "Core",
        programme: "MTECH",
        original_lecture: 1,
        original_tutorial: 2,
        original_practical: 0,
        credits: 3,
        lecture_batches: 1,
        tutorial_batches: 14,
        total_lecture: 1,
        total_tutorial: 28,
        total_practical: 0,
        alloted_lecture: 1,
        alloted_tutorial: 13,
        alloted_practical: 0,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000408" },
    },
    {
        id: "CSET751",
        name: "vestibulum sed",
        type: "Elective",
        programme: "BCA",
        original_lecture: 2,
        original_tutorial: 0,
        original_practical: 0,
        credits: 2,
        lecture_batches: 1,
        tutorial_batches: 0,
        total_lecture: 2,
        total_tutorial: 0,
        total_practical: 0,
        alloted_lecture: 2,
        alloted_tutorial: 0,
        alloted_practical: 0,
        allotment_status: "FULL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000409" },
    },
    {
        id: "CSET433",
        name: "quis augue",
        type: "Core",
        programme: "BTECH",
        original_lecture: 4,
        original_tutorial: 1,
        original_practical: 4,
        credits: 7,
        lecture_batches: 4,
        tutorial_batches: 11,
        total_lecture: 16,
        total_tutorial: 11,
        total_practical: 44,
        alloted_lecture: 16,
        alloted_tutorial: 0,
        alloted_practical: 4,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d00040a" },
    },
    {
        id: "CSET902",
        name: "erat curabitur gravida",
        type: "Core",
        programme: "BCA",
        original_lecture: 2,
        original_tutorial: 0,
        original_practical: 0,
        credits: 2,
        lecture_batches: 3,
        tutorial_batches: 0,
        total_lecture: 6,
        total_tutorial: 0,
        total_practical: 0,
        alloted_lecture: 5,
        alloted_tutorial: 0,
        alloted_practical: 0,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d00040b" },
    },
    {
        id: "CSET984",
        name: "volutpat convallis morbi",
        type: "Elective",
        programme: "PHD",
        original_lecture: 2,
        original_tutorial: 1,
        original_practical: 0,
        credits: 3,
        lecture_batches: 5,
        tutorial_batches: 17,
        total_lecture: 10,
        total_tutorial: 17,
        total_practical: 0,
        alloted_lecture: 9,
        alloted_tutorial: 16,
        alloted_practical: 0,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d00040c" },
    },
    {
        id: "CSET673",
        name: "aliquet maecenas leo",
        type: "Elective",
        programme: "BCA",
        original_lecture: 0,
        original_tutorial: 1,
        original_practical: 0,
        credits: 1,
        lecture_batches: 0,
        tutorial_batches: 17,
        total_lecture: 0,
        total_tutorial: 17,
        total_practical: 0,
        alloted_lecture: 0,
        alloted_tutorial: 17,
        alloted_practical: 0,
        allotment_status: "FULL",
        _id: { $oid: "63fa0e2ffc13ae3c1d00040d" },
    },
    {
        id: "CSET100",
        name: "lacinia eget tincidunt",
        type: "Core",
        programme: "MTECH",
        original_lecture: 0,
        original_tutorial: 1,
        original_practical: 0,
        credits: 1,
        lecture_batches: 0,
        tutorial_batches: 10,
        total_lecture: 0,
        total_tutorial: 10,
        total_practical: 0,
        alloted_lecture: 0,
        alloted_tutorial: 6,
        alloted_practical: 0,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d00040e" },
    },
    {
        id: "CSET376",
        name: "natoque penatibus et",
        type: "Core",
        programme: "BCA",
        original_lecture: 2,
        original_tutorial: 2,
        original_practical: 2,
        credits: 5,
        lecture_batches: 5,
        tutorial_batches: 11,
        total_lecture: 10,
        total_tutorial: 22,
        total_practical: 22,
        alloted_lecture: 8,
        alloted_tutorial: 10,
        alloted_practical: 18,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d00040f" },
    },
    {
        id: "CSET685",
        name: "maecenas leo",
        type: "Core",
        programme: "MTECH",
        original_lecture: 4,
        original_tutorial: 2,
        original_practical: 4,
        credits: 8,
        lecture_batches: 1,
        tutorial_batches: 3,
        total_lecture: 4,
        total_tutorial: 6,
        total_practical: 12,
        alloted_lecture: 3,
        alloted_tutorial: 4,
        alloted_practical: 7,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000410" },
    },
    {
        id: "CSET697",
        name: "eget congue eget",
        type: "Elective",
        programme: "BCA",
        original_lecture: 2,
        original_tutorial: 2,
        original_practical: 0,
        credits: 4,
        lecture_batches: 5,
        tutorial_batches: 4,
        total_lecture: 10,
        total_tutorial: 8,
        total_practical: 0,
        alloted_lecture: 4,
        alloted_tutorial: 8,
        alloted_practical: 0,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000411" },
    },
    {
        id: "CSET651",
        name: "sapien urna",
        type: "Core",
        programme: "MTECH",
        original_lecture: 2,
        original_tutorial: 2,
        original_practical: 0,
        credits: 4,
        lecture_batches: 3,
        tutorial_batches: 4,
        total_lecture: 6,
        total_tutorial: 8,
        total_practical: 0,
        alloted_lecture: 0,
        alloted_tutorial: 4,
        alloted_practical: 0,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000412" },
    },
    {
        id: "CSET598",
        name: "sed tristique in",
        type: "Core",
        programme: "MTECH",
        original_lecture: 0,
        original_tutorial: 0,
        original_practical: 2,
        credits: 1,
        lecture_batches: 0,
        tutorial_batches: 10,
        total_lecture: 0,
        total_tutorial: 0,
        total_practical: 20,
        alloted_lecture: 0,
        alloted_tutorial: 0,
        alloted_practical: 5,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000413" },
    },
    {
        id: "CSET161",
        name: "accumsan tortor quis",
        type: "Elective",
        programme: "MTECH",
        original_lecture: 1,
        original_tutorial: 2,
        original_practical: 4,
        credits: 5,
        lecture_batches: 1,
        tutorial_batches: 7,
        total_lecture: 1,
        total_tutorial: 14,
        total_practical: 28,
        alloted_lecture: 1,
        alloted_tutorial: 14,
        alloted_practical: 16,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000414" },
    },
    {
        id: "CSET123",
        name: "est risus auctor",
        type: "Elective",
        programme: "MTECH",
        original_lecture: 3,
        original_tutorial: 2,
        original_practical: 0,
        credits: 5,
        lecture_batches: 2,
        tutorial_batches: 14,
        total_lecture: 6,
        total_tutorial: 28,
        total_practical: 0,
        alloted_lecture: 2,
        alloted_tutorial: 4,
        alloted_practical: 0,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000415" },
    },
    {
        id: "CSET261",
        name: "volutpat dui maecenas",
        type: "Elective",
        programme: "MTECH",
        original_lecture: 2,
        original_tutorial: 2,
        original_practical: 0,
        credits: 4,
        lecture_batches: 5,
        tutorial_batches: 15,
        total_lecture: 10,
        total_tutorial: 30,
        total_practical: 0,
        alloted_lecture: 0,
        alloted_tutorial: 10,
        alloted_practical: 0,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000416" },
    },
    {
        id: "CSET243",
        name: "quam sapien",
        type: "Core",
        programme: "BTECH",
        original_lecture: 3,
        original_tutorial: 1,
        original_practical: 2,
        credits: 5,
        lecture_batches: 4,
        tutorial_batches: 14,
        total_lecture: 12,
        total_tutorial: 14,
        total_practical: 28,
        alloted_lecture: 1,
        alloted_tutorial: 3,
        alloted_practical: 20,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000417" },
    },
    {
        id: "CSET254",
        name: "auctor gravida sem",
        type: "Elective",
        programme: "BCA",
        original_lecture: 2,
        original_tutorial: 0,
        original_practical: 4,
        credits: 4,
        lecture_batches: 4,
        tutorial_batches: 17,
        total_lecture: 8,
        total_tutorial: 0,
        total_practical: 68,
        alloted_lecture: 8,
        alloted_tutorial: 0,
        alloted_practical: 25,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000418" },
    },
    {
        id: "CSET723",
        name: "pede justo",
        type: "Elective",
        programme: "MTECH",
        original_lecture: 4,
        original_tutorial: 2,
        original_practical: 0,
        credits: 6,
        lecture_batches: 4,
        tutorial_batches: 4,
        total_lecture: 16,
        total_tutorial: 8,
        total_practical: 0,
        alloted_lecture: 5,
        alloted_tutorial: 0,
        alloted_practical: 0,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000419" },
    },
    {
        id: "CSET344",
        name: "volutpat convallis",
        type: "Elective",
        programme: "PHD",
        original_lecture: 1,
        original_tutorial: 2,
        original_practical: 4,
        credits: 5,
        lecture_batches: 6,
        tutorial_batches: 9,
        total_lecture: 6,
        total_tutorial: 18,
        total_practical: 36,
        alloted_lecture: 5,
        alloted_tutorial: 6,
        alloted_practical: 5,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d00041a" },
    },
    {
        id: "CSET152",
        name: "mauris eget",
        type: "Elective",
        programme: "BCA",
        original_lecture: 2,
        original_tutorial: 2,
        original_practical: 4,
        credits: 6,
        lecture_batches: 4,
        tutorial_batches: 1,
        total_lecture: 8,
        total_tutorial: 2,
        total_practical: 4,
        alloted_lecture: 1,
        alloted_tutorial: 2,
        alloted_practical: 0,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d00041b" },
    },
    {
        id: "CSET883",
        name: "platea dictumst",
        type: "Core",
        programme: "MTECH",
        original_lecture: 3,
        original_tutorial: 2,
        original_practical: 2,
        credits: 6,
        lecture_batches: 1,
        tutorial_batches: 2,
        total_lecture: 3,
        total_tutorial: 4,
        total_practical: 4,
        alloted_lecture: 0,
        alloted_tutorial: 2,
        alloted_practical: 2,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d00041c" },
    },
    {
        id: "CSET914",
        name: "lobortis sapien",
        type: "Elective",
        programme: "BTECH",
        original_lecture: 0,
        original_tutorial: 0,
        original_practical: 0,
        credits: 0,
        lecture_batches: 0,
        tutorial_batches: 0,
        total_lecture: 0,
        total_tutorial: 0,
        total_practical: 0,
        alloted_lecture: 0,
        alloted_tutorial: 0,
        alloted_practical: 0,
        allotment_status: "FULL",
        _id: { $oid: "63fa0e2ffc13ae3c1d00041d" },
    },
    {
        id: "CSET128",
        name: "nibh fusce lacus",
        type: "Elective",
        programme: "BCA",
        original_lecture: 4,
        original_tutorial: 0,
        original_practical: 4,
        credits: 6,
        lecture_batches: 3,
        tutorial_batches: 9,
        total_lecture: 12,
        total_tutorial: 0,
        total_practical: 36,
        alloted_lecture: 1,
        alloted_tutorial: 0,
        alloted_practical: 12,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d00041e" },
    },
    {
        id: "CSET298",
        name: "porttitor lacus at",
        type: "Elective",
        programme: "MTECH",
        original_lecture: 4,
        original_tutorial: 1,
        original_practical: 2,
        credits: 6,
        lecture_batches: 5,
        tutorial_batches: 15,
        total_lecture: 20,
        total_tutorial: 15,
        total_practical: 30,
        alloted_lecture: 4,
        alloted_tutorial: 6,
        alloted_practical: 16,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d00041f" },
    },
    {
        id: "CSET294",
        name: "nonummy integer",
        type: "Elective",
        programme: "PHD",
        original_lecture: 4,
        original_tutorial: 0,
        original_practical: 4,
        credits: 6,
        lecture_batches: 2,
        tutorial_batches: 9,
        total_lecture: 8,
        total_tutorial: 0,
        total_practical: 36,
        alloted_lecture: 8,
        alloted_tutorial: 0,
        alloted_practical: 13,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000420" },
    },
    {
        id: "CSET365",
        name: "tempus sit",
        type: "Core",
        programme: "BCA",
        original_lecture: 0,
        original_tutorial: 0,
        original_practical: 0,
        credits: 0,
        lecture_batches: 0,
        tutorial_batches: 0,
        total_lecture: 0,
        total_tutorial: 0,
        total_practical: 0,
        alloted_lecture: 0,
        alloted_tutorial: 0,
        alloted_practical: 0,
        allotment_status: "FULL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000421" },
    },
    {
        id: "CSET543",
        name: "amet nunc viverra",
        type: "Elective",
        programme: "PHD",
        original_lecture: 2,
        original_tutorial: 1,
        original_practical: 0,
        credits: 3,
        lecture_batches: 3,
        tutorial_batches: 1,
        total_lecture: 6,
        total_tutorial: 1,
        total_practical: 0,
        alloted_lecture: 0,
        alloted_tutorial: 0,
        alloted_practical: 0,
        allotment_status: "NONE",
        _id: { $oid: "63fa0e2ffc13ae3c1d000422" },
    },
    {
        id: "CSET594",
        name: "diam erat fermentum",
        type: "Core",
        programme: "MTECH",
        original_lecture: 0,
        original_tutorial: 2,
        original_practical: 4,
        credits: 4,
        lecture_batches: 0,
        tutorial_batches: 7,
        total_lecture: 0,
        total_tutorial: 14,
        total_practical: 28,
        alloted_lecture: 0,
        alloted_tutorial: 10,
        alloted_practical: 12,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000423" },
    },
    {
        id: "CSET010",
        name: "ac consequat",
        type: "Core",
        programme: "PHD",
        original_lecture: 4,
        original_tutorial: 2,
        original_practical: 0,
        credits: 6,
        lecture_batches: 4,
        tutorial_batches: 4,
        total_lecture: 16,
        total_tutorial: 8,
        total_practical: 0,
        alloted_lecture: 11,
        alloted_tutorial: 2,
        alloted_practical: 0,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000424" },
    },
    {
        id: "CSET415",
        name: "nulla suspendisse",
        type: "Core",
        programme: "PHD",
        original_lecture: 4,
        original_tutorial: 1,
        original_practical: 4,
        credits: 7,
        lecture_batches: 3,
        tutorial_batches: 2,
        total_lecture: 12,
        total_tutorial: 2,
        total_practical: 8,
        alloted_lecture: 8,
        alloted_tutorial: 0,
        alloted_practical: 8,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000425" },
    },
    {
        id: "CSET668",
        name: "nulla nisl",
        type: "Core",
        programme: "MTECH",
        original_lecture: 3,
        original_tutorial: 2,
        original_practical: 0,
        credits: 5,
        lecture_batches: 6,
        tutorial_batches: 4,
        total_lecture: 18,
        total_tutorial: 8,
        total_practical: 0,
        alloted_lecture: 14,
        alloted_tutorial: 5,
        alloted_practical: 0,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000426" },
    },
    {
        id: "CSET458",
        name: "amet eros",
        type: "Core",
        programme: "BCA",
        original_lecture: 1,
        original_tutorial: 1,
        original_practical: 2,
        credits: 3,
        lecture_batches: 4,
        tutorial_batches: 18,
        total_lecture: 4,
        total_tutorial: 18,
        total_practical: 36,
        alloted_lecture: 3,
        alloted_tutorial: 12,
        alloted_practical: 2,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000427" },
    },
    {
        id: "CSET608",
        name: "dui vel nisl",
        type: "Elective",
        programme: "MTECH",
        original_lecture: 4,
        original_tutorial: 0,
        original_practical: 4,
        credits: 6,
        lecture_batches: 3,
        tutorial_batches: 10,
        total_lecture: 12,
        total_tutorial: 0,
        total_practical: 40,
        alloted_lecture: 1,
        alloted_tutorial: 0,
        alloted_practical: 21,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000428" },
    },
    {
        id: "CSET034",
        name: "curae donec pharetra",
        type: "Elective",
        programme: "PHD",
        original_lecture: 3,
        original_tutorial: 0,
        original_practical: 0,
        credits: 3,
        lecture_batches: 5,
        tutorial_batches: 0,
        total_lecture: 15,
        total_tutorial: 0,
        total_practical: 0,
        alloted_lecture: 13,
        alloted_tutorial: 0,
        alloted_practical: 0,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000429" },
    },
    {
        id: "CSET521",
        name: "curae nulla",
        type: "Elective",
        programme: "PHD",
        original_lecture: 2,
        original_tutorial: 2,
        original_practical: 4,
        credits: 6,
        lecture_batches: 4,
        tutorial_batches: 9,
        total_lecture: 8,
        total_tutorial: 18,
        total_practical: 36,
        alloted_lecture: 7,
        alloted_tutorial: 15,
        alloted_practical: 30,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d00042a" },
    },
    {
        id: "CSET147",
        name: "eros elementum",
        type: "Core",
        programme: "BCA",
        original_lecture: 4,
        original_tutorial: 0,
        original_practical: 0,
        credits: 4,
        lecture_batches: 2,
        tutorial_batches: 0,
        total_lecture: 8,
        total_tutorial: 0,
        total_practical: 0,
        alloted_lecture: 5,
        alloted_tutorial: 0,
        alloted_practical: 0,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d00042b" },
    },
    {
        id: "CSET567",
        name: "aenean fermentum donec",
        type: "Elective",
        programme: "BTECH",
        original_lecture: 3,
        original_tutorial: 0,
        original_practical: 4,
        credits: 5,
        lecture_batches: 2,
        tutorial_batches: 1,
        total_lecture: 6,
        total_tutorial: 0,
        total_practical: 4,
        alloted_lecture: 0,
        alloted_tutorial: 0,
        alloted_practical: 1,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d00042c" },
    },
    {
        id: "CSET445",
        name: "porttitor pede",
        type: "Elective",
        programme: "MTECH",
        original_lecture: 2,
        original_tutorial: 0,
        original_practical: 2,
        credits: 3,
        lecture_batches: 4,
        tutorial_batches: 8,
        total_lecture: 8,
        total_tutorial: 0,
        total_practical: 16,
        alloted_lecture: 0,
        alloted_tutorial: 0,
        alloted_practical: 12,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d00042d" },
    },
    {
        id: "CSET238",
        name: "nullam orci pede",
        type: "Elective",
        programme: "MTECH",
        original_lecture: 3,
        original_tutorial: 2,
        original_practical: 2,
        credits: 6,
        lecture_batches: 3,
        tutorial_batches: 18,
        total_lecture: 9,
        total_tutorial: 36,
        total_practical: 36,
        alloted_lecture: 6,
        alloted_tutorial: 33,
        alloted_practical: 19,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d00042e" },
    },
    {
        id: "CSET465",
        name: "et ultrices",
        type: "Core",
        programme: "BTECH",
        original_lecture: 1,
        original_tutorial: 2,
        original_practical: 4,
        credits: 5,
        lecture_batches: 4,
        tutorial_batches: 16,
        total_lecture: 4,
        total_tutorial: 32,
        total_practical: 64,
        alloted_lecture: 1,
        alloted_tutorial: 29,
        alloted_practical: 1,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d00042f" },
    },
    {
        id: "CSET135",
        name: "sapien cum sociis",
        type: "Core",
        programme: "BCA",
        original_lecture: 2,
        original_tutorial: 2,
        original_practical: 0,
        credits: 4,
        lecture_batches: 1,
        tutorial_batches: 2,
        total_lecture: 2,
        total_tutorial: 4,
        total_practical: 0,
        alloted_lecture: 0,
        alloted_tutorial: 1,
        alloted_practical: 0,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000430" },
    },
    {
        id: "CSET245",
        name: "nibh fusce lacus",
        type: "Elective",
        programme: "BTECH",
        original_lecture: 1,
        original_tutorial: 2,
        original_practical: 4,
        credits: 5,
        lecture_batches: 2,
        tutorial_batches: 2,
        total_lecture: 2,
        total_tutorial: 4,
        total_practical: 8,
        alloted_lecture: 2,
        alloted_tutorial: 2,
        alloted_practical: 5,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000431" },
    },
    {
        id: "CSET615",
        name: "sit amet lobortis",
        type: "Elective",
        programme: "BTECH",
        original_lecture: 0,
        original_tutorial: 0,
        original_practical: 0,
        credits: 0,
        lecture_batches: 0,
        tutorial_batches: 0,
        total_lecture: 0,
        total_tutorial: 0,
        total_practical: 0,
        alloted_lecture: 0,
        alloted_tutorial: 0,
        alloted_practical: 0,
        allotment_status: "FULL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000432" },
    },
    {
        id: "CSET609",
        name: "porttitor pede",
        type: "Core",
        programme: "MTECH",
        original_lecture: 1,
        original_tutorial: 0,
        original_practical: 0,
        credits: 1,
        lecture_batches: 5,
        tutorial_batches: 0,
        total_lecture: 5,
        total_tutorial: 0,
        total_practical: 0,
        alloted_lecture: 1,
        alloted_tutorial: 0,
        alloted_practical: 0,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000433" },
    },
    {
        id: "CSET751",
        name: "ridiculus mus vivamus",
        type: "Elective",
        programme: "MTECH",
        original_lecture: 3,
        original_tutorial: 1,
        original_practical: 4,
        credits: 6,
        lecture_batches: 1,
        tutorial_batches: 8,
        total_lecture: 3,
        total_tutorial: 8,
        total_practical: 32,
        alloted_lecture: 2,
        alloted_tutorial: 5,
        alloted_practical: 15,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000434" },
    },
    {
        id: "CSET755",
        name: "at dolor quis",
        type: "Elective",
        programme: "BTECH",
        original_lecture: 2,
        original_tutorial: 2,
        original_practical: 0,
        credits: 4,
        lecture_batches: 4,
        tutorial_batches: 3,
        total_lecture: 8,
        total_tutorial: 6,
        total_practical: 0,
        alloted_lecture: 5,
        alloted_tutorial: 5,
        alloted_practical: 0,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000435" },
    },
    {
        id: "CSET836",
        name: "dictumst aliquam",
        type: "Core",
        programme: "MTECH",
        original_lecture: 3,
        original_tutorial: 2,
        original_practical: 4,
        credits: 7,
        lecture_batches: 4,
        tutorial_batches: 2,
        total_lecture: 12,
        total_tutorial: 4,
        total_practical: 8,
        alloted_lecture: 12,
        alloted_tutorial: 4,
        alloted_practical: 7,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e2ffc13ae3c1d000436" },
    },
    {
        id: "CSET895",
        name: "fringilla rhoncus mauris",
        type: "Elective",
        programme: "PHD",
        original_lecture: 2,
        original_tutorial: 0,
        original_practical: 0,
        credits: 2,
        lecture_batches: 2,
        tutorial_batches: 0,
        total_lecture: 4,
        total_tutorial: 0,
        total_practical: 0,
        alloted_lecture: 3,
        alloted_tutorial: 0,
        alloted_practical: 0,
        allotment_status: "PARTIAL",
        _id: { $oid: "63fa0e30fc13ae3c1d000437" },
    },
];
