export const teachers = [
    {
        id: { $oid: "64046dc4fc13ae4fa700010e" },
        name: "Scotty Yepiskopov",
        preffered_mode: "LTP",
        email: "syepiskopov0@ibm.com",
        assigned_status: "FULL",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa700010f" },
        name: "Emmy Mawer",
        preffered_mode: "TPL",
        email: "emawer1@baidu.com",
        assigned_status: "PART",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000110" },
        name: "Felice Lockier",
        preffered_mode: "PTL",
        email: "flockier2@yellowpages.com",
        assigned_status: "FULL",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000111" },
        name: "Mycah Ferrieri",
        preffered_mode: "LPT",
        email: "mferrieri3@list-manage.com",
        assigned_status: "FULL",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000112" },
        name: "Lanae Delue",
        preffered_mode: "LPT",
        email: "ldelue4@wordpress.org",
        assigned_status: "NONE",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000113" },
        name: "Bianka Assandri",
        preffered_mode: "LPT",
        email: "bassandri5@de.vu",
        assigned_status: "FULL",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000114" },
        name: "Sada Yashaev",
        preffered_mode: "LTP",
        email: "syashaev6@vistaprint.com",
        assigned_status: "PART",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000115" },
        name: "Ashlen Poupard",
        preffered_mode: "TLP",
        email: "apoupard7@bandcamp.com",
        assigned_status: "NONE",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000116" },
        name: "Blanca McCallion",
        preffered_mode: "TPL",
        email: "bmccallion8@forbes.com",
        assigned_status: "NONE",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000117" },
        name: "Kris Bend",
        preffered_mode: "LPT",
        email: "kbend9@examiner.com",
        assigned_status: "NONE",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000118" },
        name: "Alvie McKibbin",
        preffered_mode: "LTP",
        email: "amckibbina@e-recht24.de",
        assigned_status: "PART",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000119" },
        name: "Annadiane Touson",
        preffered_mode: "TLP",
        email: "atousonb@yahoo.co.jp",
        assigned_status: "NONE",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa700011a" },
        name: "Conney McKinty",
        preffered_mode: "TLP",
        email: "cmckintyc@ucla.edu",
        assigned_status: "FULL",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa700011b" },
        name: "Mirabella Brunelleschi",
        preffered_mode: "PLT",
        email: "mbrunelleschid@google.com.hk",
        assigned_status: "FULL",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa700011c" },
        name: "Fidelity McIvor",
        preffered_mode: "PTL",
        email: "fmcivore@homestead.com",
        assigned_status: "NONE",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa700011d" },
        name: "Purcell Lennie",
        preffered_mode: "TLP",
        email: "plennief@mac.com",
        assigned_status: "FULL",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa700011e" },
        name: "Trevor Pridden",
        preffered_mode: "PTL",
        email: "tpriddeng@virginia.edu",
        assigned_status: "FULL",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa700011f" },
        name: "Eba Hanley",
        preffered_mode: "TLP",
        email: "ehanleyh@cam.ac.uk",
        assigned_status: "PART",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000120" },
        name: "Mac Munt",
        preffered_mode: "TPL",
        email: "mmunti@clickbank.net",
        assigned_status: "PART",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000121" },
        name: "Zaneta Hukin",
        preffered_mode: "LPT",
        email: "zhukinj@craigslist.org",
        assigned_status: "PART",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000122" },
        name: "Aveline Bansal",
        preffered_mode: "LTP",
        email: "abansalk@weebly.com",
        assigned_status: "PART",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000123" },
        name: "Alfy Salvin",
        preffered_mode: "LTP",
        email: "asalvinl@furl.net",
        assigned_status: "PART",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000124" },
        name: "Bat MacRury",
        preffered_mode: "TPL",
        email: "bmacrurym@devhub.com",
        assigned_status: "FULL",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000125" },
        name: "Jennette Dering",
        preffered_mode: "LTP",
        email: "jderingn@amazon.co.jp",
        assigned_status: "FULL",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000126" },
        name: "Jocko Tenney",
        preffered_mode: "TLP",
        email: "jtenneyo@xinhuanet.com",
        assigned_status: "NONE",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000127" },
        name: "Gideon Rosterne",
        preffered_mode: "PTL",
        email: "grosternep@imdb.com",
        assigned_status: "PART",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000128" },
        name: "Ora Zebedee",
        preffered_mode: "PTL",
        email: "ozebedeeq@symantec.com",
        assigned_status: "FULL",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000129" },
        name: "Cathyleen Knoles",
        preffered_mode: "PTL",
        email: "cknolesr@51.la",
        assigned_status: "NONE",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa700012a" },
        name: "Cassius Nerney",
        preffered_mode: "PTL",
        email: "cnerneys@hostgator.com",
        assigned_status: "PART",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa700012b" },
        name: "Josias Finci",
        preffered_mode: "PLT",
        email: "jfincit@deviantart.com",
        assigned_status: "FULL",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa700012c" },
        name: "Thalia Frenchum",
        preffered_mode: "TLP",
        email: "tfrenchumu@google.de",
        assigned_status: "NONE",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa700012d" },
        name: "Josey Neads",
        preffered_mode: "LTP",
        email: "jneadsv@google.com.hk",
        assigned_status: "NONE",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa700012e" },
        name: "Ashia Valde",
        preffered_mode: "PLT",
        email: "avaldew@alexa.com",
        assigned_status: "FULL",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa700012f" },
        name: "Alfons Hodge",
        preffered_mode: "LTP",
        email: "ahodgex@npr.org",
        assigned_status: "NONE",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000130" },
        name: "Wilt Swannick",
        preffered_mode: "PTL",
        email: "wswannicky@discovery.com",
        assigned_status: "FULL",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000131" },
        name: "Art Goldup",
        preffered_mode: "PLT",
        email: "agoldupz@lulu.com",
        assigned_status: "PART",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000132" },
        name: "Stormy Wartnaby",
        preffered_mode: "LTP",
        email: "swartnaby10@ted.com",
        assigned_status: "FULL",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000133" },
        name: "Baudoin Jarratt",
        preffered_mode: "TLP",
        email: "bjarratt11@cargocollective.com",
        assigned_status: "NONE",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000134" },
        name: "Aguistin Hrynczyk",
        preffered_mode: "TLP",
        email: "ahrynczyk12@statcounter.com",
        assigned_status: "PART",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000135" },
        name: "Kerrie Tasseler",
        preffered_mode: "TLP",
        email: "ktasseler13@macromedia.com",
        assigned_status: "FULL",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000136" },
        name: "Merilyn Pascho",
        preffered_mode: "PLT",
        email: "mpascho14@ebay.co.uk",
        assigned_status: "PART",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000137" },
        name: "Roarke Hegden",
        preffered_mode: "TLP",
        email: "rhegden15@hhs.gov",
        assigned_status: "PART",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000138" },
        name: "Francklyn Snoxall",
        preffered_mode: "PLT",
        email: "fsnoxall16@engadget.com",
        assigned_status: "PART",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa7000139" },
        name: "Wendell Carty",
        preffered_mode: "PTL",
        email: "wcarty17@independent.co.uk",
        assigned_status: "FULL",
    },
    {
        id: { $oid: "64046dc4fc13ae4fa700013a" },
        name: "Xavier Clulow",
        preffered_mode: "TLP",
        email: "xclulow18@adobe.com",
        assigned_status: "FULL",
    },
];
