export const teachers = [
    {
        id: { $oid: "63fb68ebfc13ae5f1e000009" },
        name: "Britta Dradey",
        email: "bdradey0@wufoo.com",
        prefferred_mode: "TPL",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e00000a" },
        name: "Aveline Slayford",
        email: "aslayford1@answers.com",
        prefferred_mode: "TLP",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e00000b" },
        name: "Gwenore Margaret",
        email: "gmargaret2@ft.com",
        prefferred_mode: "PLT",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e00000c" },
        name: "Niki Eskriett",
        email: "neskriett3@si.edu",
        prefferred_mode: "TLP",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e00000d" },
        name: "Claribel Billyard",
        email: "cbillyard4@technorati.com",
        prefferred_mode: "PLT",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e00000e" },
        name: "Torin Keiley",
        email: "tkeiley5@nyu.edu",
        prefferred_mode: "LPT",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e00000f" },
        name: "Friedrick Verrills",
        email: "fverrills6@quantcast.com",
        prefferred_mode: "LPT",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e000010" },
        name: "Zarah Knewstubb",
        email: "zknewstubb7@latimes.com",
        prefferred_mode: "PLT",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e000011" },
        name: "Laura Hanse",
        email: "lhanse8@ibm.com",
        prefferred_mode: "LPT",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e000012" },
        name: "Jarrod Arnaudon",
        email: "jarnaudon9@1688.com",
        prefferred_mode: "TPL",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e000013" },
        name: "Fabian Spini",
        email: "fspinia@google.ru",
        prefferred_mode: "LTP",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e000014" },
        name: "Johnath Ditzel",
        email: "jditzelb@theglobeandmail.com",
        prefferred_mode: "PLT",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e000015" },
        name: "Marta Denman",
        email: "mdenmanc@time.com",
        prefferred_mode: "LTP",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e000016" },
        name: "Rozanna Hitzke",
        email: "rhitzked@bloomberg.com",
        prefferred_mode: "TLP",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e000017" },
        name: "Thorvald Mathwen",
        email: "tmathwene@sbwire.com",
        prefferred_mode: "PTL",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e000018" },
        name: "Shem Petris",
        email: "spetrisf@tinypic.com",
        prefferred_mode: "PTL",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e000019" },
        name: "Jemima Kuhle",
        email: "jkuhleg@stanford.edu",
        prefferred_mode: "TPL",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e00001a" },
        name: "Sonia Reary",
        email: "srearyh@yahoo.com",
        prefferred_mode: "TPL",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e00001b" },
        name: "Edithe Burgane",
        email: "eburganei@miibeian.gov.cn",
        prefferred_mode: "LTP",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e00001c" },
        name: "Lil Winspear",
        email: "lwinspearj@merriam-webster.com",
        prefferred_mode: "PTL",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e00001d" },
        name: "Kore Peete",
        email: "kpeetek@adobe.com",
        prefferred_mode: "TPL",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e00001e" },
        name: "Peg Jezzard",
        email: "pjezzardl@wired.com",
        prefferred_mode: "PTL",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e00001f" },
        name: "Silvain Bellee",
        email: "sbelleem@seesaa.net",
        prefferred_mode: "PLT",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e000020" },
        name: "Jobi Ainslee",
        email: "jainsleen@wikimedia.org",
        prefferred_mode: "TLP",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e000021" },
        name: "Jacintha Hedlestone",
        email: "jhedlestoneo@yahoo.com",
        prefferred_mode: "LPT",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e000022" },
        name: "Emelen Callender",
        email: "ecallenderp@ibm.com",
        prefferred_mode: "LPT",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e000023" },
        name: "Winfield Vicarey",
        email: "wvicareyq@bloomberg.com",
        prefferred_mode: "LPT",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e000024" },
        name: "Kata Moorerud",
        email: "kmoorerudr@vkontakte.ru",
        prefferred_mode: "TPL",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e000025" },
        name: "Gilberte Chadwyck",
        email: "gchadwycks@simplemachines.org",
        prefferred_mode: "TLP",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e000026" },
        name: "Diego Bessom",
        email: "dbessomt@vistaprint.com",
        prefferred_mode: "LTP",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e000027" },
        name: "Toby Spenclay",
        email: "tspenclayu@amazon.co.uk",
        prefferred_mode: "PTL",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e000028" },
        name: "Hugo Filipov",
        email: "hfilipovv@webnode.com",
        prefferred_mode: "PLT",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e000029" },
        name: "Tedie Kleinschmidt",
        email: "tkleinschmidtw@netscape.com",
        prefferred_mode: "LTP",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e00002a" },
        name: "Consolata Boscott",
        email: "cboscottx@jalbum.net",
        prefferred_mode: "LPT",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e00002b" },
        name: "Ronda Acres",
        email: "racresy@tiny.cc",
        prefferred_mode: "PLT",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e00002c" },
        name: "Hastie Cunnane",
        email: "hcunnanez@yahoo.com",
        prefferred_mode: "LTP",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e00002d" },
        name: "Christian Hauxwell",
        email: "chauxwell10@360.cn",
        prefferred_mode: "LTP",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e00002e" },
        name: "Calhoun Ricold",
        email: "cricold11@ox.ac.uk",
        prefferred_mode: "PLT",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e00002f" },
        name: "Blakeley Demogeot",
        email: "bdemogeot12@uol.com.br",
        prefferred_mode: "LPT",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e000030" },
        name: "Salli Culpan",
        email: "sculpan13@dailymotion.com",
        prefferred_mode: "LTP",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e000031" },
        name: "Anthiathia Kopfer",
        email: "akopfer14@marriott.com",
        prefferred_mode: "LPT",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e000032" },
        name: "Zolly Biffin",
        email: "zbiffin15@deviantart.com",
        prefferred_mode: "TPL",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e000033" },
        name: "Madalyn Tregale",
        email: "mtregale16@berkeley.edu",
        prefferred_mode: "LTP",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e000034" },
        name: "Curtis Carnall",
        email: "ccarnall17@intel.com",
        prefferred_mode: "PTL",
    },
    {
        id: { $oid: "63fb68ebfc13ae5f1e000035" },
        name: "Tess Loveless",
        email: "tloveless18@ow.ly",
        prefferred_mode: "TPL",
    },
];
