name: test, build & publish backend 

on:
  push:
    paths:
      - "**.py"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    branches: [ "main" ]
  
  # publish on releases, e.g. v2.1.13 (image tagged as "2.1.13" - "v" prefix is removed)
  release:
    types: [published]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9, "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd backend
        python manage.py test
  
  docker-publish:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3

      # https://github.community/t/github-actions-repository-name-must-be-lowercase/184924
      - name: downcase REPO
        run: |
          echo "REPO_LC=${GITHUB_REPOSITORY,,}" "-backend" >>${GITHUB_ENV}
      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${REPO_LC}
          github_token: ${{ secrets.GITHUB_TOKEN }}
